FROM ubuntu:16.04

RUN \
  apt-get update && \
  apt-get install -y default-jre && \
  apt-get install -y wget && \
  wget --directory-prefix=/opt/ https://artifacts.elastic.co/downloads/logstash/logstash-6.0.0-rc2.deb && \
  dpkg -i /opt/logstash-6.0.0-rc2.deb && \
  wget --directory-prefix=/opt/ https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0-rc2.deb && \
  dpkg -i /opt/elasticsearch-6.0.0-rc2.deb && \
  apt-get install -y apt-transport-https && \
  wget --directory-prefix=/opt/ https://artifacts.elastic.co/downloads/kibana/kibana-6.0.0-rc2-amd64.deb && \
  dpkg -i /opt/kibana-6.0.0-rc2-amd64.deb && \
  service elasticsearch start && \
  service kibana start

USER elasticsearch

ENV PATH=$PATH:/usr/share/elasticsearch/bin

CMD ["elasticsearch"]

EXPOSE 9200 9300

COPY ./elk.sh .

